[package]
edition = "2021"
name = "gbe"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13"
fundsp = "0.6.5"
ringbuf = "0.2.8"
wav = "1.0.0"

[dev-dependencies]
image = "0.24.2"
